name: Spell checking
on: [pull_request, push]

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 2
    - uses: check-spelling/check-spelling@0.0.1-alpha
      env:
        bucket: ssh://git@github.com/check-spelling/examples.git
        project: spelling-data-typing
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERBOSE: 1
